[zsh] boop: make noise based on last exit code

diff --git a/zsh/.config/zsh/functions b/zsh/.config/zsh/functions
--- a/zsh/.config/zsh/functions
+++ b/zsh/.config/zsh/functions
@@ -276,6 +276,17 @@ showme() {
     cd "$tmp" || return 1
 }
 
+# Need to be a function to capture exit code
+boop () {
+  local last="$?"
+  if [[ "$last" == '0' ]]; then
+    ,make-noise notify
+  else
+    ,make-noise error
+  fi
+  $(exit "$last")
+}
+
 # Small functions (these are ideally aliases, but need args)
 
 eout() {
