[scripts] add-to-gourcer: check if url

diff --git a/scripts/.bin/add-to-gourcer b/scripts/.bin/add-to-gourcer
--- a/scripts/.bin/add-to-gourcer
+++ b/scripts/.bin/add-to-gourcer
@@ -2,9 +2,10 @@
 
 set -e
 
-if ! grep -q "$1" ~/.cache/vime/gourcer; then
+grep -q "$1" ~/.cache/vime/gourcer && echo "[Already available] $1" && exit 0
+if echo "$1" | grep -qE "^http";then
     echo "- $1" >>~/.cache/vime/gourcer
 else
-    echo "[Already available] $1"
-    # exit 1 will mess with newsboat
+    echo "[Invalid url] $1"
 fi
+# exit 1 will mess with newsboat
