[scripts] add-to-gourcer: add check to see if we have # in url
I was accidentally adding <url>#readme a lot

diff --git a/scripts/.bin/add-to-gourcer b/scripts/.bin/add-to-gourcer
--- a/scripts/.bin/add-to-gourcer
+++ b/scripts/.bin/add-to-gourcer
@@ -2,6 +2,8 @@
 
 set -e
 
+echo "$1" | grep -q '#' && echo "Invalid git url. Url contains #" && exit 1
+
 cat ~/.cache/vime/gourcer ~/Documents/Projects/projects/gourcer/pending |
 	grep -q "$1" && echo "[Already available] $1" && exit 0
 if echo "$1" | grep -qE "^http"; then
