[git] update script that checks for swear words

diff --git a/git/.git_template/hooks/pre-commit b/git/.git_template/hooks/pre-commit
--- a/git/.git_template/hooks/pre-commit
+++ b/git/.git_template/hooks/pre-commit
@@ -1,16 +1,11 @@
-#!/bin/bash
+#! /bin/bash
+SWEAR_WORDS='fuck|shit|crap|dammit|bitch|asshole' 
+CHECK=$(git diff --staged | grep "^+" | grep -Ei "$SWEAR_WORDS" -c)
 
-# Swear all you wan't until you commit
-function check_sanity(){
-    git diff | grep -i 'fuck\|shit\|crap\|dammit\|bitch\|asshole\|shithead'|wc -m
-}
-function print_insanity(){
-    git diff | grep -i 'fuck\|shit\|crap\|dammit\|bitch\|asshole\|shithead'
-}
-if [ $(check_sanity) -gt 0 ]
-    then
-        echo "Curse word found!"
-        echo ""
-        echo "$(print_insanity)"
-        exit 1
+if [[ $CHECK -gt 0 ]]
+then
+    echo "[31mAborting commmit...[00m"
+    echo "$CHECK line(s) with swear words found in the following file(s)"
+    git diff --name-only -G"$SWEAR_WORDS" | sed 's/^/> /'
+    exit 1
 fi
